-- Run this in the Supabase SQL Editor.
-- app_data stores compact metadata/settings.
-- app_sheet_rows stores large Excel sheets row-by-row.

create table if not exists public.app_data (
  sheet_name text primary key,
  data jsonb not null default '[]'::jsonb
);

create table if not exists public.app_sheet_rows (
  id bigint generated by default as identity primary key,
  sheet_name text not null,
  row_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_sheet_rows_sheet_name_id
  on public.app_sheet_rows (sheet_name, id);

alter table public.app_data enable row level security;
alter table public.app_sheet_rows enable row level security;

drop policy if exists "Allow read for anon" on public.app_data;
drop policy if exists "Allow insert and update for anon" on public.app_data;
drop policy if exists "Allow read for anon" on public.app_sheet_rows;
drop policy if exists "Allow insert and update for anon" on public.app_sheet_rows;

create policy "Allow read for anon"
  on public.app_data for select
  to anon
  using (true);

create policy "Allow insert and update for anon"
  on public.app_data for all
  to anon
  using (true)
  with check (true);

create policy "Allow read for anon"
  on public.app_sheet_rows for select
  to anon
  using (true);

create policy "Allow insert and update for anon"
  on public.app_sheet_rows for all
  to anon
  using (true)
  with check (true);
